[package]
name = "rust_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# Web framework
axum = "0.6.20"

# Asynchronous runtime
tokio = { version = "1.33.0", features = ["full"] }
